### ISSUE TITLE
Can not execute “helm repo add kafka-repo https://sir5kong.github.io/kafka-docker”

### ISSUE THREAD

**Issue by fi-ecavc** [sir5kong/kafka-docker#2]
Error: looks like "https://sir5kong.github.io/kafka-docker" is not a valid chart repository or cannot be reached: failed to fetch https://sir5kong.github.io/kafka-docker/index.yaml : 404 Not Found

**Comment by sir5kong** [comment]
问题已经解决了，感谢反馈
